[package]
name = "todo_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = {version = "0.4.39", features = ["serde"]}
clap = "4.5.23"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
